# Generated by Django 3.2.4 on 2021-08-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_content',
            new_name='comment_content',
        ),
    ]
