# Generated by Django 3.2.4 on 2021-08-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210813_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='Comments'),
        ),
    ]
