# Generated by Django 3.2.4 on 2021-08-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
    ]
